version: '3'

services:
  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data
    expose:
      - 6379

  # Kafka message broker
  # zookeeper:
  #   image: wurstmeister/zookeeper
  #   ports:
  #     - 2181:2181

  # kafka:
  #   image: wurstmeister/kafka
  #   ports:
  #     - 9092:9092
  #   links:
  #     - zookeeper:zk
  #   environment:
  #     KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
  #     KAFKA_CREATE_TOPICS: "DATA:1:1"
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock

  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
    expose:
      - 27017

  app:
    image: dmlaziuk/message-app
    # build: .
    ports:
      - 8000:80
    links:
      - redis
      - mongo
    depends_on:
      - redis
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo/messageApp
      - REDIS_URL=redis

  log:
    command: '-t 50eb48ea-92bf-4ff4-b016-3a0ed61af136'
    image: logentries/docker-logentries
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  mongo-data:
  redis-data:
